[package]
name = "day9_22"
version = "0.1.0"
authors = ["Benoît Allard <benoit.allard@gmx.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
